resource "aws_vpc" "siapp_vpc" {
    cidr_block = var.vpc_cidr
    region = var.region
    enable_dns_support = true
    enable_dns_hostnames = true
    tags={
        Name="Generated by Terraform"
    }
  
}

resource "aws_subnet" "siapp-subnets" {
    count=6
    vpc_id = aws_vpc.siapp_vpc.id
    cidr_block = cidrsubnet(var.vpc_cidr,8,count.index)   // var.subnets_cidr_ranges[count.index]
    availability_zone =var.subnets_azs[count.index]
    tags = {
      Name="siapp_dev_${var.subnets_names[count.index]}"
    }
    depends_on = [ aws_vpc.siapp_vpc ]
     
  
}
